name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
    - name: Set up JDK 17
      uses: actions/setup-java@v4.0.0
      with:
        java-version: '17'
        distribution: 'liberica'
    - name: Fix Permission
      run: |
        cd "forge 1.19.2"
        chmod +x ./gradlew
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v3.0.0-beta.4
      with:
        arguments: build
        # gradle-wrapper-path: "forge 1.19.2/gradlew"
        build-root-directory: "forge 1.19.2"
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.2.0
      with:
        path: "forge 1.19.2/build/libs"
